Iteration 13
mikesvis/short pull request #13
Opened 2024-07-13 15:09 UTC by mikesvis

Хоть у меня и была обработка на создание дубликатов всю дорогу - переделал метод в соответствии с заданием.

2024-07-16 21:53 UTC, capsulated requested changes
Коменты добавил. Если есть что-то спорное или непонятное - как обычно, можно писать в чат подгруппы или 1-1, если много вопросов

2024-07-16 21:53 UTC, capsulated commented on internal/api/api.go
> +	type BatchRequestAlias BatchRequest
А алиас зачем?

2024-07-16 21:53 UTC, capsulated commented on internal/api/api.go
> +func (c *BatchRequest) UnmarshalJSON(data []byte) error {
Я что-то даже не пойму, что это за метод))) Unmarshal должен быть где-то рядом основной с сущностью url'ов. Там должен появится, к примеру, слайс url'ов и можно добавить Marshal и Unmarshal методы для этих типов

2024-07-16 21:53 UTC, capsulated commented on internal/api/api.go
> +		CorrelationID string `json:"correlation_id"`
Я совсем не пойму, что тут присходит)) А correlation_id - это для чего?

2024-07-16 21:53 UTC, capsulated commented on internal/app/app.go
> +	storage := storage.NewStorage(config)
👍

2024-07-16 21:53 UTC, capsulated commented on internal/config/config.go
> +func (d *DBAddress) Set(flagValue string) error {
Странный, всё же, этот тип для адреса. Я бы просто строки конкантенировал и всё )) Усложняют эти методы логику. Но смотри сам, это не критично

2024-07-16 21:53 UTC, capsulated commented on internal/config/config.go
> +	*d = DBAddress(string(flagValue))
Выглядит, грубо говоря, страшно ))

2024-07-16 21:53 UTC, capsulated commented on internal/drivers/filedb/filedb.go
> +	// в мапе хранится полный урл = ключ корреляции
А зачем его в "ключ корреляции" переименовывать? Пусть так и остаётся full url ) Тоже, на твоё усмотрение

2024-07-16 21:53 UTC, capsulated commented on internal/drivers/memorymap/memorymap.go
> +type MemoryMap struct {
`MemoryStore`, `MemoryStorage`, `MemoryRepo`, `MemoryRepository` или что-то подобное будет лучше. Указывать в имени переменной особенности реализации (в нашем случае - мапа) - это антипаттерн, так как    реализация легко может измениться, а тот же функционал может быть необходим. Вдруг возьмём и переедем на redis или какую-то стороннюю библиотеку хранилки в памяти

Обязательно надо переименовать по своему вкусу

2024-07-16 21:53 UTC, capsulated commented on internal/drivers/memorymap/memorymap.go
> +	// в мапе хранится полный урл = ключ корреляции
про ключ корреляции написал выше

2024-07-16 21:53 UTC, capsulated commented on internal/drivers/postgres/postgres.go
> +type postgresDBItem struct {
А эти item нельзя сделать едиными (глобальными) для всех хранилок разве? Если можно - то лучше так и сделать. Это вообще главная сущность нашего сервиса и она по идее, будет везде появляться почти во всех наших пакетах. Хороший вариант - создать глобальный пакет для этой сущности. Могут быть как единичные urlItem, так и множественные - []urlItem `type UrlItems []UrlItem` (неминг примерный). И в этом же пакете будут всякие маршалеры и анмаршеллеры для этих типов и тп

2024-07-16 21:53 UTC, capsulated commented on internal/drivers/postgres/postgres.go
> +func bootstrapDB(db *sql.DB) error {
Обычно, создаётся init.sql для контенера с базой. Но у нас с автотестами так не сделать) Это для спраки

2024-07-16 21:53 UTC, capsulated commented on internal/drivers/postgres/postgres.go
> +	// вот это какой-то бред! как я не пытался передать в формирование запроса prepare колонку, не смог
Что-то я тоже не совсем понял, что тут за логика. Кажется, что можно упростить.

И да, выглядит как-то странно )))) И кажется, оно вообще  не надо) С виду, просто надо два разных метода сделать без switch с двумя разными селектами

2024-07-16 21:53 UTC, capsulated commented on internal/drivers/postgres/postgres.go
> +	// подход в рамках одной транзации: берем 1 элемент, смотрим есть ли он в базе,
А зачем транзакция? Есть специальные методы в библиотеке для БД, посмотри доку по внимательнее ne либe, которую используешь (в sqlx етсь спец batch запросы которые слайс могут записывать сразу, именнованные NamedExec вроде бы, в squirell специальная конструкция для подготовки таких запросов и тп). Также, есть "костыльный" способ - собрать строку (не желательный, но работающий). И select точно нужен? Было же выше использование sql конструкции `ON CONFLICT`. Также можно погуглить `INSERT OR UPDATE` / `UPSERT`. Вообще погуглить просто, batch INSERT с выбранными БД и библиотекой

2024-07-16 21:53 UTC, capsulated commented on internal/drivers/postgres/postgres.go
> +	for k, v := range us {
Ну да, `for` и  запросы к БД - это плохое сочетание ))))

2024-07-16 21:53 UTC, capsulated commented on internal/server/handler.go
> +	ctx := r.Context()
Тут может дочерний создать: `ctx := context.With???(r.Context()...)`? Можно просто с отменой и defer cancle(). Стандартный подход (мало ли захотим сами выставить таймаут иди отменить для чего-то). Думаю не критично, но обычно создаются дочерние на уровне метода

2024-07-16 21:53 UTC, capsulated commented on internal/server/handler.go
> +	ctx := r.Context()
Да и зачем для него отдельную переменную, только память тратим (совсем немного конечно, но при большом rps будет чуть заметнее). Либо создавать дочерний, либо уже прям так и передавать (но это как-то это не по канонам )))

2024-07-16 21:53 UTC, capsulated commented on internal/server/handler.go
> +	err := ge.New("bad protocol")
`errors.New` понятно, а что за `ge`? Нейминг не очень удачный

2024-07-16 21:53 UTC, capsulated commented on internal/server/handler.go
> +	var request []api.BatchRequest
По идее, надо прочитать байты body и преобразовать в слайс url'ов (к примеру, можно сделать спец конструктор для такого типа, с входным параметрам из байтов body). И если всё смаршаллилось без ошибок - слайс урлов передавать в метод хранилки и, в случае БД, batсh методом сохранить

2024-07-16 21:53 UTC, capsulated commented on internal/server/handler.go
> +	var response []api.BatchResponse
Вот сомневаюсь в доп типе для ответа, точно нужен? Мне кажется можно сделать два типа - единичная entity для url'а и слайс для множества. А далее уже преобразовывать, если необходимо. Не всегда это получается и не всегда это нужно, иногда локальные типы необходимы, нужно смотреть по ситуации. Но в идеале лучше минимизировать насколько можно количество типов, которые описывают одинаковые сущности

2024-07-16 21:53 UTC, capsulated commented on internal/server/handler.go
> +	// упарываться ответить кодом 201 если всех элементов не существовало ранее - не стал
ну если автотест пропускает - то мне особо это не важно ))

2024-07-16 21:53 UTC, capsulated commented on internal/storage/storage.go
> +	Ping(ctx context.Context) error
Ох уж этот пинг, его же не должно быть у хранилки с памятью )))

2024-07-16 21:53 UTC, capsulated commented on internal/storage/storage.go
> +		// defer db.Close() - вот с закрытием немного не ясно, поскольку тут закрытию точно не место
Всё верно, в конструкторе не должно быть. Это в `app` должно быть, но не у всех типов хранилок он есть) Решений много, но все не совсем лаконичные, будут выглядить 'костыльно'. Но может у тебя получится что-то изящное))) Может возвращать какие-то доп объекты в конструкторе (типа Pinger / Closer), и если они есть - вызывать. Либо приводить интерфейсный тип к конкретному `storage.(DbStorage).Ping()` -с добавлением проверки конфига или соответствия самого типа. Выглядит всё это не очень, нужно что-то изобрести ))) А в задании было реализовать ping, поэтому нужно сделать (для образовательных целей, по аналогии - такое тз пришло от заказчика и поменять его нельзя =)

2024-07-17 17:45 UTC, mikesvis commented on internal/storage/storage.go
> +	Ping(ctx context.Context) error
Уточните пожалуйста требования, ибо это уже вопрос к бизнесу (так как дальше есть варианты), а вопрос вот такой:
Как будет вести себя ручка `GET /ping` в случае хранилки типа `InMemory`? Какой статус, какой ответ, какая логика?

2024-07-19 14:17 UTC, mikesvis commented on internal/drivers/postgres/postgres.go
> +	// подход в рамках одной транзации: берем 1 элемент, смотрим есть ли он в базе,
Опишу что обсудили на 1-1:
1) SELECT мне нужен для того чтобы узнать короткий сгенерированный url, который был добавлен в базу ранее (в рамках другого запроса например, другим пользователем или вчера/позавчера...)
2) В задании было сказано использовать ON CONFLICT. UPDATE в этом случае мне не подойдет, т.к. я сотру предыдущий короткий url, который был добавлен в базу ранее (в рамках другого запроса например, другим пользователем или вчера/позавчера...)
3) Пример реализации INSERT построчно я взял из курса, при этом такой подход описывался как приоритетный по скорости. Также если у нас в рамках одной транзакции INSERT одной строки - то при конфликте предыдущие строки (успешные/безконфликтные) будут добавлены. Если делать batch INSERT нескольких строк в рамках одной транзакции, то в случае конфликта транзакция откатится и не будет добавлен ни один. А что дальше? Выяснять какой конфликтует и вычеркивать его из добавления (поскольку он был добавлен "вчера") и снова пытаться batch INSERT? Тогда нужно "достать" shortUrl для конфликтных строк.

У меня же все проще:
В цикле по каждому элементу смотрим, есть ли он уже в базе по fullUrl. если он есть, читаем его shortKey (старый) и забываем про него. Если элемента нет, то INSERT.

В заданиях изначально не хватает условий, что делать если элемент уже был. Генерить дубль? Про дубли упоминается только в последней итерации в этом спринте:
```
Чтобы не проверять наличие оригинального URL в базе данных отдельным запросом, можно воспользоваться конструкцией INSERT ... ON CONFLICT в PostgreSQL. Однако в таком случае придётся самостоятельно возвращать и проверять собственную ошибку.
```
Вопрос: что делать по итогу? возвращать старый сгенерированный (что впринципе правильно), или же просто статус "Conflict". Тогда при добавленнии пользователей в сервис будет деградация урлов: кто первый добавил - тот сокращение и получит. Все последующие пользователи будут получать `Conflict` вместо короткого url (хоть и сгенерированного ранее).
Я же учитывал их с самого начала сервиса, поэтому у меня конфликта и быть не должно. НО! Раз в задании указали использовать `ON CONFLICT`, то я это переделал.

Я потратил очень много времени в предыдущих спринтах на поиск ранее сгенерированных shortUrl при добавлении fullUrl. Сейчас получается что я зря это делал?

2024-07-19 19:08 UTC, mikesvis commented on internal/api/api.go
> +	type BatchRequestAlias BatchRequest
Упростил

2024-07-19 19:09 UTC, mikesvis commented on internal/api/api.go
> +func (c *BatchRequest) UnmarshalJSON(data []byte) error {
Упростил

2024-07-19 19:09 UTC, mikesvis commented on internal/api/api.go
> +		CorrelationID string `json:"correlation_id"`
Упростил

2024-07-19 19:10 UTC, mikesvis commented on internal/config/config.go
> +func (d *DBAddress) Set(flagValue string) error {
Упростил

2024-07-19 19:10 UTC, mikesvis commented on internal/config/config.go
> +	*d = DBAddress(string(flagValue))
Бес попутал, но упростил :)

2024-07-19 19:11 UTC, mikesvis commented on internal/drivers/filedb/filedb.go
> +	// в мапе хранится полный урл = ключ корреляции
Это мапа  `map[fullUrl]correlation_id` так надол ))
Обсудили 1-1

2024-07-19 19:12 UTC, mikesvis commented on internal/drivers/memorymap/memorymap.go
> +type MemoryMap struct {
Переименовал на `InMemory`

2024-07-19 19:12 UTC, mikesvis commented on internal/drivers/memorymap/memorymap.go
> +	// в мапе хранится полный урл = ключ корреляции
Угу, обсудили

2024-07-19 19:13 UTC, mikesvis commented on internal/drivers/postgres/postgres.go
> +type postgresDBItem struct {
Обсудили. Я не хочу перемешивать сущности базы с сущностями домена.

2024-07-19 19:13 UTC, mikesvis commented on internal/drivers/postgres/postgres.go
> +func bootstrapDB(db *sql.DB) error {
Угу, но пока так

2024-07-19 19:14 UTC, mikesvis commented on internal/drivers/postgres/postgres.go
> +	// вот это какой-то бред! как я не пытался передать в формирование запроса prepare колонку, не смог
Сделал 2 метода и упростил, убрал Count

2024-07-19 19:14 UTC, mikesvis commented on internal/drivers/postgres/postgres.go
> +	// подход в рамках одной транзации: берем 1 элемент, смотрим есть ли он в базе,
Я сделаль... Перевел на sqlx. Сделал batch insert. Это было самое сложное из всего.

2024-07-19 19:16 UTC, mikesvis commented on internal/drivers/postgres/postgres.go
> +	for k, v := range us {
Избавился от  сложности `O(N)`

2024-07-19 19:16 UTC, mikesvis commented on internal/server/handler.go
> +	ctx := r.Context()
Вот тут я не подумал что можно отнаследоваться (сделать дочерний). Исправил.

2024-07-19 19:17 UTC, mikesvis commented on internal/server/handler.go
> +	ctx := r.Context()
Дыа

2024-07-19 19:17 UTC, mikesvis commented on internal/server/handler.go
> +	err := ge.New("bad protocol")
сделал `_goerrors`

2024-07-19 19:17 UTC, mikesvis commented on internal/server/handler.go
> +	var request []api.BatchRequest
Это обсудили. Слайс не подойдет - нужна `map`.

2024-07-19 19:19 UTC, mikesvis commented on internal/server/handler.go
> +	var response []api.BatchResponse
Обсудили. Тут я все уростил, но структуры хочу оставить - не люблю я все в один котел, понимаю что в начале об этом думать не надо и лучше проще, но мне вероисповедание не позволяет завернуть все в одну структуру :) Слишком много я от такого в последствии избавлялся по опыту.

2024-07-19 19:21 UTC, mikesvis commented on internal/server/handler.go
> +	// упарываться ответить кодом 201 если всех элементов не существовало ранее - не стал
Нужны требачи (Бизнес требования) Про дубли написал выше, жаль что с самого начала их учитывал и тратил время :( Можно было в 13 сделать и не париться, но опыт не пропьешь :)

2024-07-19 19:22 UTC, mikesvis commented on internal/storage/storage.go
> +	Ping(ctx context.Context) error
А какие требачи?
Какой ответ должен быть если хранилка в памяти?
Внес доработку

2024-07-19 19:23 UTC, mikesvis commented on internal/storage/storage.go
> +		// defer db.Close() - вот с закрытием немного не ясно, поскольку тут закрытию точно не место
Внес доработку из серии `storage.(DbStorage).Ping()` с добавлением проверки типа

2024-07-23 00:21 UTC, capsulated commented on internal/api/api.go
> +		CorrelationID string `json:"correlation_id"`
correlation_id посмотрел в примерах в теории, это приемлемо

2024-07-23 00:24 UTC, capsulated commented on internal/config/config.go
> +	*d = DBAddress(string(flagValue))
Да не так уж и страшно-то. Создавать удобные для работы новые типы - это абсолютно правильный подход. Так как тип простой, то назначается с разименованием (на звонке 1-1 разобрались). Я тоже часто впорос просто задаю в комменте, если нет прямого призыва к действию - то можно просто ответить на вопрос))

2024-07-23 00:24 UTC, capsulated commented on internal/drivers/postgres/postgres.go
> +type postgresDBItem struct {
Ок ок

2024-07-23 00:25 UTC, capsulated commented on internal/drivers/postgres/postgres.go
> +func bootstrapDB(db *sql.DB) error {
Да, он так и останется)

2024-07-23 00:25 UTC, capsulated commented on internal/drivers/postgres/postgres.go
> +	// вот это какой-то бред! как я не пытался передать в формирование запроса prepare колонку, не смог
Да супер, в данном случае это намного лучше)

2024-07-23 00:27 UTC, capsulated commented on internal/drivers/postgres/postgres.go
> +	// подход в рамках одной транзации: берем 1 элемент, смотрим есть ли он в базе,
Можно же ON CONFLICT DO NOTHING чтобы не презаписывать... Но нам надо будет вернуть же ещё 🤔

А sqlx - это ты лихо )) Но он реально очень удобный, ИМХО, по сравнению с остальными

2024-07-23 00:29 UTC, capsulated commented on internal/drivers/postgres/postgres.go
> +	for k, v := range us {
А сложность от константы - это же неплохо. Вообще в цикле операции к БД или в цикле отправка http запросов - это явный признак, что надо упрощать)

2024-07-23 00:30 UTC, capsulated commented on internal/server/handler.go
> +	ctx := r.Context()
Ну это тоже не критично же, скорее для справки

2024-07-23 00:31 UTC, capsulated commented on internal/server/handler.go
> +	err := ge.New("bad protocol")
это тоже минорное замечание. Тогда должны быть handlersErrors (уровня хендлера)

2024-07-23 00:33 UTC, capsulated commented on internal/server/handler.go
> +	var request []api.BatchRequest
Я что-то уже забыл, а почему слайс не подойдёт? Вообще слайсы структур - это же прям правильный объект для записи в БД. С sqlx вообще идеально. Хотя в sqlx можно и мапы писать в бд, вроде

2024-07-23 00:33 UTC, capsulated commented on internal/server/handler.go
> +	// упарываться ответить кодом 201 если всех элементов не существовало ранее - не стал
У нас требования к автотесту. Если проверяет определённый статус - то ничего не поделаешь

2024-07-23 00:34 UTC, capsulated commented on internal/storage/storage.go
> +	Ping(ctx context.Context) error
Вообще поделить можно интерфейс. Но проверять нужно будет на соотвествие интерфесу

2024-07-23 00:35 UTC, capsulated commented on internal/storage/storage.go
> +		// defer db.Close() - вот с закрытием немного не ясно, поскольку тут закрытию точно не место
типа того, один из варинатов. Либо доп объекты - закрыватель, пингер или типа того, которые вызываются у нужных хранилок и игнорируются в других. Вариантов можнт быть много

2024-07-23 00:39 UTC, capsulated approved these changes
Большая работа проделана, много комментариев и исправлений. Есть большой плюс в этом - ты быстрее привыкаешь с синтаксису и структуре программы на го

Апрувлю

А в следующих спринтах уже будем смотреть, в процессе дальнейшей разработки, надо что-то переорганизовывать для удобства или нет

2024-07-23 13:57 UTC, merged