Iteration 5
mikesvis/short pull request #5
Opened 2024-06-09 12:51 UTC by mikesvis

Env config + making config simpler

2024-06-13 19:37 UTC, capsulated requested changes
В общем код организован хорошо, но есть некоторые замечания по структуре, см в коментах

2024-06-13 19:37 UTC, capsulated commented on internal/app/config/config.go
> +func (a Address) String() string {
А тут специально без указателя ресивер? Если да, то почему?

2024-06-13 19:37 UTC, capsulated commented on internal/app/config/config.go
> +package config
`app` пакет, на мой взгляд, лишний. При создании директории мы автоматически создаём пакет - это одно из существенных отличий go от других ЯП. Директория, это что-то типа namespace из других языков

Лучше создать пакеты `config`, `server`, `storage`, а `helpers` разбть бы на два независимых пакета: `urlformat`, `keygen`, так как utils, helpers и т.п -. антипаттерн, он "распухнет" с развитием проекта

2024-06-13 19:37 UTC, capsulated commented on internal/app/server/handler.go
> +func ServeGet(s storage.StorageURL) http.HandlerFunc {
Удобнее описать структурный тип с методами хендлеров. В таком формате удобнее добавлять зависимости (в нашем случае во всех хендлерах параметр хранилки), скажем если добавиться логгер, кэш, трассировка или подобное, придётся добавлять к каждому хендлеру

2024-06-13 19:37 UTC, capsulated commented on internal/app/server/server.go
> +func ShortRouter() chi.Router {
Это фактически конструктор, лучше именовать его `NewRouter() *chi.Mux { ... }` и возвращать указатель на экземпляр, а не интерфейс. Про нейминг интерфейсов [тут](https://go.dev/doc/effective_go#composite_literals)

2024-06-13 19:37 UTC, capsulated commented on internal/app/storage/storage.go
> +type StorageURL interface {
Интерфейс принято описывать в местах использования, а не реализации

2024-06-15 13:57 UTC, mikesvis commented on internal/app/config/config.go
> +func (a Address) String() string {
Видимо не совсем хорошо разобрался в теме с указателями и мной двигала идея защиты от изменения, которая тут непричем. Исправил.

2024-06-15 13:59 UTC, mikesvis commented on internal/app/config/config.go
> +package config
Реорганизовал структуру. До последнего момента хотел сделать разные пакеты для `urlformat` и `keygen`, но в виде подпапок в папке `helpers`. Не понял что я сам от этого выиграю и сделал без папки `helpers`.

2024-06-15 14:05 UTC, mikesvis commented on internal/app/server/handler.go
> +func ServeGet(s storage.StorageURL) http.HandlerFunc {
Сделал насколько хватило ума-разума. По хорошему бы конечно повторить структуру `service` `storage` `api` `model` как показали на вебинаре дабы покрыть интерфейсами где и как-надо, но пока решил оставить близко к своей структуре. Учту на будущее.

2024-06-15 14:07 UTC, mikesvis commented on internal/app/server/server.go
> +func ShortRouter() chi.Router {
Про конструкторы понял, но так же элегантно как в примере (в одну строчку) с описанием роутинга не смог придуать как реализовать. Поменял возвращаемый тип.

2024-06-15 14:08 UTC, mikesvis commented on internal/app/storage/storage.go
> +type StorageURL interface {
Как говорил выше по хорошему бы структуру видоизменить. Возможно столкнусь в дальнейшем и переделаю. Пока что вынес интерфейс отдельно от реализации storage.

2024-06-17 20:37 UTC, capsulated commented on internal/app/config/config.go
> +func (a Address) String() string {
Это надо обязательно разобраться) Поэтому вопрос такой оставил. Много уже и видео и статей по этой теме: "передача параметров по указателю или по значению".

2024-06-17 20:40 UTC, capsulated commented on internal/app/server/server.go
> +func ShortRouter() chi.Router {
Это вообще не критично, чуть чуть проще будет читать в будущем

2024-06-17 20:46 UTC, capsulated approved these changes
Да, всё круто!

2024-06-17 20:46 UTC, capsulated commented on internal/server/handler.go
> +	return func(w http.ResponseWriter, r *http.Request) {
Тут уже можно убрать возвращаемую функцию на обычную сигнатуру: 
```go
func (h *handler) ServePost() (w http.ResponseWriter, r *http.Request) { ... }
```

Но в таком случае, "гибкость" кода становиться меньше.
Так что, смотри сам, как лучше

2024-06-21 08:47 UTC, merged