Iteration 9
mikesvis/short pull request #9
Opened 2024-06-27 16:27 UTC by mikesvis

Add file storage

2024-06-30 16:57 UTC, capsulated requested changes
Добавил комментарии. Если с чем-то не согласен - ответ на комментарий приветствуется, но обязательно аргументированный. В крайнем случае 1-1.

2024-06-30 16:57 UTC, capsulated commented on internal/compressor/compressor.go
> +package compressor
`compressor` можно переместить в корень из `internal`. А ещё лучше - в `pkg/compressor`, что бы можно было импортировать, скажем, в выпускной работе или в pet проекте

2024-06-30 16:57 UTC, capsulated commented on internal/compressor/compressor.go
> +func init() {
Функции `init()` очень "опасны", в связи с тем, что через некоторое время можно забыть о скрытой инициализации. Использовать `init()` нужно только в самом крайнем случае, а в большинстве - сделать инициализацию явной с помощью фабричного метода - `func New(...) *Exemplar`

2024-06-30 16:57 UTC, capsulated commented on internal/config/config.go
>  func InitConfig() {
Тут так же: сделать конструктор по-хорошему. `func New() *Config` - такая конструкция гибче, так как можно будет экземпляр привести к интерфейсу  и заменять реализацию в случае необходимости

2024-06-30 16:57 UTC, capsulated commented on internal/config/config.go
> +func GetFileStoragePath() string {
Если реализовать создание экземпляра через конструктор - то в большинстве случаев можно будет просто читать поля экземпляра, если конфиг будет передаваться по указателю, а не через интерфейс. А необходимость в геттерах и сеттерах появляется только при появлении интерфейса

2024-06-30 16:57 UTC, capsulated commented on internal/logger/logger.go
> +var Log *zap.SugaredLogger
Так же, хорошо бы избавиться от глобальной переменной с помощью конструктора-фабрики

2024-06-30 16:57 UTC, capsulated commented on internal/logger/logger.go
> +func RequestResponseLogger(next http.Handler) http.Handler {
Это обязательно перенести из пакета logger в независимый пакет middleware. Хороший пример у [chi](https://github.com/go-chi/chi/tree/master/middleware)

2024-06-30 16:57 UTC, capsulated commented on internal/server/contract.go
> +	GetByFull(fullURL string) (domain.URL, bool)
А почему `bool`? Может сразу универсальный подход с выходным параметром типа `error`?

2024-06-30 16:57 UTC, capsulated commented on internal/server/handler.go
>  	return func(w http.ResponseWriter, r *http.Request) {
Тут, в принципе,  можно сразу сигнатуру оставить без 'обёртки':
```go
func (h *handler) ServeGet() (w http.ResponseWriter, r *http.Request) { ... }
```

2024-06-30 16:57 UTC, capsulated commented on internal/server/handler.go
> +func (h *handler) ServeAPIPost() http.HandlerFunc {
Не очень удачное имя для метода. `CreateShortUrl` к примеру, лучше, так как в таком имени содержится однозначное описание функционала. А реализацию (post, get, head, slice, array) в именах лучше  использовать, так как реализация может поменяться. И `ServeGet` также, переименовать как нибудь, к примеру `GetFullUrl` или что-то похожее

2024-06-30 16:57 UTC, capsulated commented on internal/server/handler_test.go
> +func init() {
В тестах - ок, но повторюсь - 'скрытые' init очень коварны, лучше в самом крайнем случае использовать

2024-06-30 16:57 UTC, capsulated commented on internal/server/server.go
> +	s = newStorage(config.GetFileStoragePath())
Кстати, конструкторы в конструкторах надо минимизировать на сколько возможно. Лучше так:
```go
func NewRouter(cfg *Config, storage Storager, handlers *Handlers) *chi.Mux { 
   router := &Router{
       cfg: cfg,
       storage: storage,
       ...
   }
   ...
}
```
А конструкторы вызывать уровнем выше и передавать экзмепляры в конструкторы через параметры. Это паттерн - DI.

2024-06-30 16:57 UTC, capsulated commented on internal/server/server.go
> +func newStorage(fileStoragePath string) StorageURL {
Это обязательно перенести в пакет `storage`!

2024-06-30 16:57 UTC, capsulated commented on internal/server/server.go
>  func Run() error {
Тогда, по-хорошему, создать новый тип/пакет - например `app` - с конструктором `NewApp()` и методом Run(). И его вызывать в `cmd`

2024-06-30 16:57 UTC, capsulated commented on internal/storage/filedb/storage.go
> +type item struct {
А почему не экспортируемый тип? Он, разве, не используется в других пакетах? Либо дублируется. И немного уточнить нейминг в идеале, типа может `UrlItem` или `ShortUrl`  🤔 Нужно подумать

2024-06-30 16:57 UTC, capsulated commented on internal/storage/filedb/storage.go
> +func NewStorageURL(fileName string) *storageURL {
По идее, если конструктор экспортируемый, то и тип выходного значения нужно тоже сделать экпортируемым. Работать всё равно будет, но у меня Goland ругается на такое

2024-06-30 16:57 UTC, capsulated commented on internal/storage/memorymap/storage.go
> +func (s *storageURL) GetByFull(fullURL string) (domain.URL, bool) {
Как уже написал выше, лучше `error` возвращать

2024-06-30 16:57 UTC, capsulated commented on internal/urlformat/urlformal.go
>  func ValidateURL(URL string) error {
Также, претендент на переезд в `pkg`

2024-07-02 19:59 UTC, mikesvis commented on internal/server/handler.go
>  	return func(w http.ResponseWriter, r *http.Request) {
А тут точно в исправлении сигнатура имеет возвращаемые параметры? А то я уже весь мозг сломал.

2024-07-02 20:06 UTC, mikesvis commented on internal/server/contract.go
> +	GetByFull(fullURL string) (domain.URL, bool)
Задумка была такая что поскольку мы под интерфейсом, в реализациях может быть обработка различных ошибок. А вот отсутствие элемента это не совсем ошибка, поскольку дальнейшая логика сохраняет новый элемент. Если переделать на error, то придется классифицировать ошибки на «логические» (отсутствие элемента) и «кодовые»(например отвал базы)

2024-07-02 20:09 UTC, mikesvis commented on internal/compressor/compressor.go
> +func init() {
Подозревал, но за неимением опыта выбрал исходя из знаний. С замечанием согласен, буду думать.

2024-07-02 20:13 UTC, mikesvis commented on internal/storage/filedb/storage.go
> +type item struct {
В моменте мысль шла в сторону того что это одна из реализаций хранилища. Внутренняя кухня. Зачем кому-то знать про эту структуру если формат у нее свой и специфичный?

2024-07-03 11:53 UTC, mikesvis commented on internal/server/server.go
> +func newStorage(fileStoragePath string) StorageURL {
Огребаю проблем с циклической зависимостью. Видимо структура была не очень в прошлый раз

2024-07-03 12:14 UTC, mikesvis commented on internal/logger/logger.go
> +func RequestResponseLogger(next http.Handler) http.Handler {
Попытался понять что там. Не понял как это сконструировать у меня (начиная от структуры)
Например папка `internal/middleware`. Не понимаю что в ней подразумевается? Нужен ли файл `middleware.go` - какая у него ответственнось, будет ли он "собирать" все middleware в какую-нибудь структуру? Начинаю немного паниковать что даже если успею после консультации понять что делать после этого ревью, то скорее всего не устею следующий спринт (разница 4 дня по дедлайнам)  :(

2024-07-03 12:17 UTC, mikesvis commented on internal/config/config.go
>  func InitConfig() {
Пока что локально внес правку, но требуется переработка в проекте. Как говорил выше: пока что это камень преткновения для меня. Правки будут обширные по проекту.

2024-07-03 12:17 UTC, mikesvis commented on internal/config/config.go
> +func GetFileStoragePath() string {
См. коммент выше

2024-07-03 12:17 UTC, mikesvis commented on internal/logger/logger.go
> +var Log *zap.SugaredLogger
Как говорил выше: пока что это камень преткновения для меня. Правки будут обширные по проекту.

2024-07-03 12:20 UTC, mikesvis commented on internal/server/handler.go
> +func (h *handler) ServeAPIPost() http.HandlerFunc {
Это пока самое простое, есть только непонимание как разрулить 2 одинаковых по ответственности метода. Один пользуется plain/text, второй application/json. Пока локально сделал как
`GetFullURL()`
`CreateShortURL()` `CreateShortURLJSON()`
`Fail()`

2024-07-03 12:21 UTC, mikesvis commented on internal/server/server.go
> +	s = newStorage(config.GetFileStoragePath())
Это к вопросу о конструкторах, требуется переработка в проекте. Как говорил выше: пока что это камень преткновения для меня. Правки будут обширные по проекту.

2024-07-03 12:22 UTC, mikesvis commented on internal/server/server.go
>  func Run() error {
Какие там будут зависимости. Надо будет черепанить на фоне всего проекта.

2024-07-03 12:23 UTC, mikesvis commented on internal/storage/memorymap/storage.go
> +func (s *storageURL) GetByFull(fullURL string) (domain.URL, bool) {
Упоминал мой вопрос и мой посыл выше

2024-07-03 12:23 UTC, mikesvis commented on internal/urlformat/urlformal.go
>  func ValidateURL(URL string) error {
Сделаю, это просто.

2024-07-04 21:45 UTC, mikesvis commented on internal/compressor/compressor.go
> +package compressor
Перенес.  Но теперь мне не нравится что есть `middleware/logger.go` и `pkg/compressor/compressor.go` - вообще чтобы в такую конструкцию прокинуть свое значение это какой-то мрак. Я так и не разобрался до конца как сделать так что `middleware` был с своей микрологикой и принимал какой-либо аргумент (сделал из примеров chi) и потом чтобы этот агрумент участвовал в `middleware` хендлер функции.

Вот например: есть `middleware/compressor` он сейчас и в `pkg` у меня сам по себе довольно страшный поскольку надо капитально разобраться в логике. Где-то сджимаем, а где-то нет, где-то выходим из ф-ции досрочно поскольку разжимать не надо, а где-то делаем полезную работу дальше. Чтобы еще и ридеры врайтеры утащить - я б вообще наверное такого не сделал в обозримом будущем.

Как вот сделать что бы `middleware` вернул ф-цию для chi, но например на вход `middleware` можно передать любой компрессор (а их реализация уже в `pkg`)? Сегодня хочу `GZIP` завтра другой? Это для меня пока что какой-то космос...

2024-07-04 21:47 UTC, mikesvis commented on internal/compressor/compressor.go
> +func init() {
Для себя определил так: есть некий слой инициализации приложения - все конструкторы туда. На `go` надо привыкнуть к этому, особенно когда начинается полиморфизм, тогда все становится вообще неочевидно.

2024-07-04 21:48 UTC, mikesvis commented on internal/config/config.go
>  func InitConfig() {
Это про конструкторы. Писал выше

2024-07-04 21:48 UTC, mikesvis commented on internal/config/config.go
> +func GetFileStoragePath() string {
Это про конструкторы. Писал выше

2024-07-04 21:48 UTC, mikesvis commented on internal/logger/logger.go
> +var Log *zap.SugaredLogger
Это про конструкторы. Писал выше

2024-07-04 21:49 UTC, mikesvis commented on internal/logger/logger.go
> +func RequestResponseLogger(next http.Handler) http.Handler {
Тоже указал что в голове в первом комменте. Пока что мрак.

2024-07-04 21:50 UTC, mikesvis commented on internal/server/contract.go
> +	GetByFull(fullURL string) (domain.URL, bool)
Сделал 2 параметра в возврате: объект и честный `error` на будущее. Сравниваю с пустым объектом.

2024-07-04 21:51 UTC, mikesvis commented on internal/server/handler.go
>  	return func(w http.ResponseWriter, r *http.Request) {
Обсудили 1-1

2024-07-04 21:52 UTC, mikesvis commented on internal/server/handler.go
> +func (h *handler) ServeAPIPost() http.HandlerFunc {
Переименовал - только детализировал до `Text` и `JSON` поскольку два метода как две капли воды но с разными `Content-Type`

2024-07-04 21:53 UTC, mikesvis commented on internal/server/handler_test.go
> +func init() {
Вроде когде перешел на конструкторы поубирал, но возможно где-то пропустил. Постарался прибраться вобщем :)

2024-07-04 21:54 UTC, mikesvis commented on internal/server/server.go
> +	s = newStorage(config.GetFileStoragePath())
Вот тут я так и не понял до конца зачем структура `Router` в примере. Может позже пойму.

2024-07-04 21:57 UTC, mikesvis commented on internal/server/server.go
> +func newStorage(fileStoragePath string) StorageURL {
Вынес в отдельный пакет `storage` и его ответственность теперь только выбор типа хранилки и описан интерфейс.
Хранилку в файлах и памяти убрал из пространства `storage` пока в `internal` но возможно лучше как-то сгруппировать куда-то типа `drivers` или `providers`

2024-07-04 21:59 UTC, mikesvis commented on internal/server/server.go
>  func Run() error {
Cделал как понял - в `app.New()` теперь вся инициализация (кроме *chi.Router - не придумал как его утащить по человечески)

2024-07-04 21:59 UTC, mikesvis commented on internal/storage/filedb/storage.go
> +type item struct {
Переименовал как обсудили

2024-07-04 22:02 UTC, mikesvis commented on internal/storage/filedb/storage.go
> +func NewStorageURL(fileName string) *storageURL {
Не понял зачем это, но навсякий случай сделал :) Вот кто полезет плюхаться с этим типом - есть же интерфейс? Нечего туда лазить - пользуйтесь интерфейсом, но согласен, сам интерфейс должен быть доступен :)

2024-07-04 22:03 UTC, mikesvis commented on internal/storage/memorymap/storage.go
> +func (s *storageURL) GetByFull(fullURL string) (domain.URL, bool) {
Описал выше. Зря затеял второй параметр. Оставил бы один - не мучался бы, зато теперь есть ошибки.

2024-07-04 22:04 UTC, mikesvis commented on internal/urlformat/urlformal.go
>  func ValidateURL(URL string) error {
Перенес. Самое простое из всего что было.

2024-07-08 11:10 UTC, capsulated commented on internal/compressor/compressor.go
> +func init() {
Тут в рамках спринтов можно что-то рефакторить. Я вообщем озвучил классический подход, а где использовать `init()`, а где `New()` уже решай сам) Но один совет, с `init()` лучше не увлекаться, иначе могут появляться такие же, как сам init, скрытые ошибки

2024-07-08 11:12 UTC, capsulated commented on internal/logger/logger.go
> +var Log *zap.SugaredLogger
Если что - пиши в чат подгруппы, тегай, можно со снипеттами кода - всё разберём, если потребуется

2024-07-08 11:14 UTC, capsulated commented on internal/logger/logger.go
> +func RequestResponseLogger(next http.Handler) http.Handler {
Давай тогда скорее на 1-1 )))) Голосом такое намного быстрее обсудить. Только выпиши вопросы заранее обязательно, тогда точно всё успеем обсудить.

Мидлвари - это функции, которые просто импортируешь и подключаешь при создании роутера. Так что чего-то общего не надо, это будет в конструкторе (или назначении) роутеру хендлеров

2024-07-08 11:16 UTC, capsulated commented on internal/server/handler.go
>  	return func(w http.ResponseWriter, r *http.Request) {
Да, прошу прощения, очепятка)

2024-07-08 11:17 UTC, capsulated commented on internal/server/server.go
> +	s = newStorage(config.GetFileStoragePath())
Это как один из вариантов, можно отдельный тип для роутера создать, а можно и не создавать

2024-07-08 11:18 UTC, capsulated commented on internal/server/server.go
> +func newStorage(fileStoragePath string) StorageURL {
Лучше `storage`, тогда сразу ясно, что это за пакет. Так что всё супер

2024-07-08 11:18 UTC, capsulated commented on internal/server/server.go
>  func Run() error {
Всё супер, всё правильно сделал! )))

2024-07-08 11:19 UTC, capsulated commented on internal/storage/filedb/storage.go
> +type item struct {
А, ну смотри, если внутренняя - тогда ок. Да, отлично переименовал - сразу ясно, что за тип

2024-07-08 11:23 UTC, capsulated approved these changes
Всё отлично! Все замечания пофиксил, как и написал в комментариях. 

Если какие-то вопросы о том, почему так или непонятные моменты - пиши в подгруппе, тегай, добавляй снипет с кодом, всё разберём. Либо 1-1 если набралось много неясных моментов

А так всё супер, апрувлю

2024-07-08 11:44 UTC, merged